### ISSUE TITLE
Make a script to find if a track has lyrics available using Musixmatch API

### ISSUE THREAD

**Issue by Ares358** [Ares358/Twitter_LyricBot#28]
Use the Musixmatch API to make a script that takes a song and an artist name as input and checks if its lyrics are available and add the song+artist name in the specified format if it doesn't already exist in `Fav_list.txt`.

**Comment by ShlokMohanty** [comment]
@Ares358 can i take on this issue ? Can you assign me this issue?

**Comment by Ares358** [comment]
Sure! Go ahead!

**Comment by ShlokMohanty** [comment]
thanks @Ares358  for assigning me this task

**Comment by ShlokMohanty** [comment]
@Ares358 what is the deadline for submitting the changes to this pr ?

**Comment by Ares358** [comment]
No specific deadlines. A few days sound fair enough taking into consideration that most of what's required is already readily available via APIs.

**Comment by ShlokMohanty** [comment]
@Ares358 thanks on it 
just solving the issue today will be able to solve within day after tomorrow will that be okay?

**Comment by Ares358** [comment]
Sure
Sounds good!

**Comment by ShlokMohanty** [comment]
Todays progress: 

looked at the code base for a better understanding 
and now would be contributing to this issue tomorrow 
@Ares358 is that comfortable for you ?

**Comment by Ares358** [comment]
Sure!

**Comment by ShlokMohanty** [comment]
@Ares358 sorry for being inactive this week will be doing it and finishing it soon i know it is easy was just going through the code base i would be updating on a daily basis.

**Comment by Ares358** [comment]
Hey @ShlokMohanty. Any updates yet? It'd be totally alright if you want someone else to be assigned this just in case.

**Comment by ShlokMohanty** [comment]
@Ares358 yes was busy till yesterday now its all fine now I will able to complete it

**Comment by ShlokMohanty** [comment]
would be giving you daily updates

**Comment by ShlokMohanty** [comment]
@Ares358  this was my yesterday's update :
1) Musixmatch API : where I learn't the basics 
before that I was learning about other api's like how we call an API without writing the actual scripts and then would be moving further with writing API musixmatch scripts : 

Musixmatch link : https://developer.musixmatch.com/documentation

2) postman-api 
link: https://learning.postman.com/docs/getting-started/introduction/
