### ISSUE TITLE
Add your favourite songs to the list

### ISSUE THREAD

**Issue by Ares358** [Ares358/Twitter_LyricBot#3]
Add your favourite songs and their artist in the _**Fav_list.txt**_ file.

The **format** is **{Song name}-{Artist name}**

Make sure you **append** your entries above the _'---END---'_ line

**Comment by GC2002** [comment]
we have to make a list of the text file?

**Comment by Ares358** [comment]
> 
> 
> we have to make a list of the text file?

The text file already exists(named Fav_list.txt) with some data in it already. You can fork the project and add more entries into the file.

**Comment by Ares358** [comment]
> 
> 
> Can multiple people do this?

Yes! The more, the better!

**Comment by Ares358** [comment]
> 
> 
> @Ares358 Sweet, I just submitted a pull request then!

Merged ^__^

**Comment by umer2001** [comment]
I am on it too...

**Comment by Frozenbloo** [comment]
Just Submitted a Pull Request of my favourites.
