### ISSUE TITLE
Write missing module/function docstrings

### ISSUE THREAD

**Issue by Ares358** [Ares358/Twitter_LyricBot#35]
## Description
The module/function docstrings are missing. 

## Occurrences
There are 14 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Ares358/Twitter_LyricBot/issue/PY-D0003/occurrences/](https://deepsource.io/gh/Ares358/Twitter_LyricBot/issue/PY-D0003/occurrences/)

**Comment by akshaykumar46** [comment]
please assign it to me. I want to write docstrings for some of these 14 functions
