### ISSUE TITLE
Fix indentation in TwitterBot.py

### ISSUE THREAD

**Issue by Ares358** [Ares358/Twitter_LyricBot#42]
## Description
PEP8 recommends that Python code indentation be a multiple of four.

## Occurrences
There are 30 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Ares358/Twitter_LyricBot/issue/FLK-E111/occurrences/](https://deepsource.io/gh/Ares358/Twitter_LyricBot/issue/FLK-E111/occurrences/)

**Comment by DFAWX31** [comment]
Can I take up this issue?

**Comment by Ares358** [comment]
Go ahead @DFAWX31 
Make sure all the occurrences are fixed
Assigned it to you
